<?php
/*
 * YAYA CMS - Generated by Installer
 * Do not modify this file directly.
 */
define('DB_HOST', 'localhost');
define('DB_NAME', 'church_management');
define('DB_USER', 'church_admin');
define('DB_PASS', 'password');

try {
    $pdo = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PASS);
    $pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException $e) {
    // Using a more user-friendly error message for production
    die('Database connection failed. Please check your configuration or contact support.');
}
?>