<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>YAYA CMS Installer - Step 2</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body {
            background-color: #f8f9fa;
        }
        .installer-container {
            max-width: 600px;
            margin: 50px auto;
            background: #fff;
            padding: 30px;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }
    </style>
</head>
<body>
    <div class="installer-container">
        <h2 class="text-center mb-4">Database Details</h2>
        <p>Please provide your database connection details. The installer will also create the necessary tables.</p>

        <?php
        if (isset($_POST['submit'])) {
            $db_host = $_POST['db_host'];
            $db_name = $_POST['db_name'];
            $db_user = $_POST['db_user'];
            $db_pass = $_POST['db_pass'];
            $error = null;

            try {
                // 1. Check for necessary permissions and files before attempting connection
                if (!is_writable('../config/')) {
                    throw new Exception("The directory '../config/' is not writable. Please check the folder permissions.");
                }
                if (!is_readable('schema.sql')) {
                    throw new Exception("The 'schema.sql' file is not readable. Please ensure the file exists and has the correct permissions.");
                }

                // 2. Establish database connection
                $dbh = new PDO("mysql:host=$db_host", $db_user, $db_pass, [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION
                ]);

                // 3. Create and select the database
                $dbh->exec("CREATE DATABASE IF NOT EXISTS `$db_name`;");
                $dbh->exec("USE `$db_name`;");

                // 4. Read and execute the schema file statement by statement
                $sql = file_get_contents('schema.sql');
                $statements = array_filter(array_map('trim', explode(';', $sql)));

                foreach ($statements as $statement) {
                    $dbh->exec($statement);
                }

                // 5. Create the configuration file
                $config_content = "<?php
/*
 * YAYA CMS - Generated by Installer
 * Do not modify this file directly.
 */
define('DB_HOST', '$db_host');
define('DB_NAME', '$db_name');
define('DB_USER', '$db_user');
define('DB_PASS', '$db_pass');

try {
    \$pdo = new PDO('mysql:host=' . DB_HOST . ';dbname=' . DB_NAME, DB_USER, DB_PASS);
    \$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
} catch (PDOException \$e) {
    // Using a more user-friendly error message for production
    die('Database connection failed. Please check your configuration or contact support.');
}
?>";

                if (file_put_contents('../config/db_connect.php', $config_content) === false) {
                     throw new Exception("Failed to write the configuration file to '../config/db_connect.php'.");
                }

                // 6. Redirect to the next step
                header('Location: step3.php');
                exit();

            } catch (Exception $e) {
                $error = $e->getMessage();
            }

            if ($error) {
                echo '<div class="alert alert-danger">' . htmlspecialchars($error) . '</div>';
            }
        }
        ?>

        <form method="post">
            <div class="mb-3">
                <label for="db_host" class="form-label">Database Host</label>
                <input type="text" class="form-control" id="db_host" name="db_host" value="localhost" required>
            </div>
            <div class="mb-3">
                <label for="db_name" class="form-label">Database Name</label>
                <input type="text" class="form-control" id="db_name" name="db_name" required>
            </div>
            <div class="mb-3">
                <label for="db_user" class="form-label">Database User</label>
                <input type="text" class="form-control" id="db_user" name="db_user" required>
            </div>
            <div class="mb-3">
                <label for="db_pass" class="form-label">Database Password</label>
                <input type="password" class="form-control" id="db_pass" name="db_pass">
            </div>
            <div class="d-grid">
                <button type="submit" name="submit" class="btn btn-primary">Install Schema & Proceed</button>
            </div>
        </form>
    </div>
</body>
</html>
